server.port=${PORT:8080}
spring.sql.init.encoding=UTF-8

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


spring.mail.host=smtp.mailgun.org
spring.mail.port=2525
spring.mail.username=pharmaciemailbox@sandbox09fe026c51b2484d9179348850ed33fd.mailgun.org

spring.mail.password=${MAILGUN_SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


app.mail.from=postmaster@sandbox09fe026c51b2484d9179348850ed33fd.mailgun.org


spring.data.rest.base-path=api
spring.jackson.serialization.indent-output=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


logging.level.org.springframework.mail=DEBUG
logging.pattern.console=%clr(%-5p) %cyan(%logger{15}) - %msg %n